[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "netlify-plugin-cypress"

[[redirects]]
  from = "/"
  to = "/blocked.html"
  status = 200
  force = true
  conditions = {Country = ["US"]}
